name: RainbowFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.2.0
description: Plugin for the RainbowFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, PieGuy7896, FoxIshDaBest]